"use strict";

goog.provide("Blockly.ScratchMsgs.allLocales");

goog.require("Blockly.ScratchMsgs");

Blockly.ScratchMsgs.locales["en"] = {
    MINI_SETUP: "Mini Begin %1 UART:%2 Baud:%3",
    MINI_SETUP2: "Setup %1 Loop %2",
    MINI_SETRGB: "Mini RGB LED %1 R:%2 G:%3 B:%4",
    MINI_MSET: "Mini DC Motor %1 Speed:%2",
    MINI_RCSET: "Mini Servo Motor %1 Angle:%2",
    MINI_BTNGET: "Mini Button %1 Status",
    MINI_USGET: "Mini Ultrasonic %1 Distance(cm)",
    MINI_DIGET: "Mini %1 Digital Signal",
    MINI_AIGET: "Mini %1 Analog Signal",
    MINI_DOSET: "Mini %1 Set to %2",
    MINI_I2C_MXCOLOR_SETGAMMA: "Color Sensor %1 Set Gamma correction to %2",
    MINI_I2C_MXCOLOR_GETCOLORNUMBER: "Color Sensor %1 Read Color Number",
    MINI_I2C_MXCOLOR_GETCOLOR: "Color Sensor %1 Color %2 Value",
    MINI_I2C_MXMOTION_SETFILTER: "Motion Sensor %1 Set Filter to %2",
    MINI_I2C_MXMOTION_GETACCEL: "Motion Sensor %1 Read %2 Axis Acceleration",
    MINI_I2C_MXMOTION_GETGYRO: "Motion Sensor %1 Read %2 Axis Gyroscope",
    MINI_I2C_MXMOTION_GETEULAR: "Motion Sensor %1 Eular Angle %2",
    MINI_I2C_MXLASER_GETDISTANCE: "Laser Sensor %1 Distance(mm)",
    MINI_I2C_MXMOTOR_SETPWM: "DC Box %1 %2 Set Speed %3",
    MINI_I2C_MXSERVO_SETANGLE: "RC Box %1 %2 Set Angle %3",
    MINI_I2C_MXCTRL_MOTORSET: "MATRIXController %1 %2 Set Speed %3",
    MINI_I2C_MXCTRL_MOTORROUND: "MATRIX Controller %1 %2 Rotate Rounds %3",
    MINI_I2C_MXCTRL_MOTORINVERT: "MATRIX Controller %1 %2 Set Inversion to %3",
    MINI_I2C_MXCTRL_SERVOSET: "MATRIX Controller %1 %2 Set Angle %3",
    MINI_I2C_PIXYCAM_PIXYINIT: "Pixy2 Camera %1 Begin",
    MINI_I2C_PIXYCAM_GETBLOCK: "Pixy2 Camera %1 Polling Block Information",
    MINI_I2C_PIXYCAM_INFO: "Pixy2 Camera %1 Read %2 Value",
    MINI_I2C_HTCOLOR_GETCOLORNUMBER: "HTColor %1 Color Number",
    MINI_I2C_HTCOLOR_GETRED: "HTColor %1 Red Value",
    MINI_I2C_HTCOMPASS_GETHEADING: "HTCompass %1 Compass Heading Value",
    MINI_PS2_BEGIN: "MJ2 Joystick Begin",
    MINI_PS2_POLLING: "MJ2 Joystick Polling Data",
    MINI_PS2_BTN: "Is MJ2 Joystick %1 Button Pressed?",
    MINI_PS2_JOY: "MJ2 Joystick %1 %2 Stick Value",
    MINI_SERIAL_PRINT: "Serial Print %1",
    MINI_SERIAL_PRINTLN: "Serial Print %1 with New Line",
    MINI_SERIAL_WRITE: "Serial Write (ASCII) %1",
    MINI_SERIAL_PRINTAXIS: "Serial Chart DataSet %1 %2 %3, Interval %4 ms",
    MINI_SERIAL_AVAILABLE: "Is Serial Available?",
    MINI_SERIAL_READ: "Serial Received Data (ASCII)",
    MINI_MILLIS: "Program Execution Time (Milliseconds)",
    MINI_RANDOMSEED: "Set Random Seed to %1",
    MINI_MAP: "Map %1 from %2~%3 to %4~%5",
    MINI_TIMER_RESET: "Timer %1 Reset",
    MINI_TIMER_READ: "Timer %1 Time (msec)",
    MINI_MVISION_BEGIN: "MVision Begin", 
    MINI_MVISION_READ1: "MVision Polling, Data Available", 
    MINI_MVISION_READ2: "Not Available", 
    MINI_MVISION_GETDATA: "MVision %1 Data",
    MINI_HUSKYLENS_BEGIN: "HUSKYLENS Begin(UART 9600)", 
    MINI_HUSKYLENS_POLLING: "HUSKYLENS Polling", 
    MINI_HUSKYLENS_GETBLOCK: "HUSKYLENS Block%1Data", 
    MINI_HUSKYLENS_GETARROW: "HUSKYLENS Arrow%1Data", 
    MINI_HUSKYLENS_ISDETECT: "HUSKYLENS Is object detected?", 
    MINI_PLACEHOLDER: "-------------------------------",
    CATEGORY__MINI: "Mini Core",
    CATEGORY__MINI_SERIAL: "Serial",
    CATEGORY__MINI_MJ2: "MJ2 Joystick",
    CATEGORY__MINI_SENSORS: "Sensing",
    CATEGORY__MINI_BOXS: "Extension Boxs",
    CATEGORY__MINI_THRDPTY: "3rd Party Sensors",
    MINICAT_PLACEHOLDER: "-------------------------------",
    CONTROL_FOREVER: "forever",
    CONTROL_REPEAT: "repeat %1",
    CONTROL_IF: "if %1 then",
    CONTROL_ELSE: "else",
    CONTROL_STOP: "stop",
    CONTROL_STOP_ALL: "all",
    CONTROL_STOP_THIS: "this script",
    CONTROL_STOP_OTHER: "other scripts in sprite",
    CONTROL_WAIT: "wait %1 millisecond",
    CONTROL_WAITUNTIL: "wait until %1",
    CONTROL_REPEATUNTIL: "repeat until %1",
    CONTROL_WHILE: "while %1",
    CONTROL_FOREACH: "for each %1 in %2",
    CONTROL_STARTASCLONE: "when I start as a clone",
    CONTROL_CREATECLONEOF: "create clone of %1",
    CONTROL_CREATECLONEOF_MYSELF: "myself",
    CONTROL_DELETETHISCLONE: "delete this clone",
    CONTROL_COUNTER: "counter",
    CONTROL_INCRCOUNTER: "increment counter",
    CONTROL_CLEARCOUNTER: "clear counter",
    CONTROL_ALLATONCE: "all at once",
    DATA_SETVARIABLETO: "set %1 to %2",
    DATA_CHANGEVARIABLEBY: "change %1 by %2",
    DATA_SHOWVARIABLE: "show variable %1",
    DATA_HIDEVARIABLE: "hide variable %1",
    DATA_ADDTOLIST: "add %1 to %2",
    DATA_DELETEOFLIST: "delete %1 of %2",
    DATA_DELETEALLOFLIST: "delete all of %1",
    DATA_INSERTATLIST: "insert %1 at %2 of %3",
    DATA_REPLACEITEMOFLIST: "replace item %1 of %2 with %3",
    DATA_ITEMOFLIST: "item %1 of %2",
    DATA_ITEMNUMOFLIST: "item # of %1 in %2",
    DATA_LENGTHOFLIST: "length of %1",
    DATA_LISTCONTAINSITEM: "%1 contains %2?",
    DATA_SHOWLIST: "show list %1",
    DATA_HIDELIST: "hide list %1",
    DATA_INDEX_ALL: "all",
    DATA_INDEX_LAST: "last",
    DATA_INDEX_RANDOM: "random",
    EVENT_WHENFLAGCLICKED: "when %1 clicked",
    EVENT_WHENTHISSPRITECLICKED: "when this sprite clicked",
    EVENT_WHENSTAGECLICKED: "when stage clicked",
    EVENT_WHENTOUCHINGOBJECT: "when this sprite touches %1",
    EVENT_WHENBROADCASTRECEIVED: "when I receive %1",
    EVENT_WHENBACKDROPSWITCHESTO: "when backdrop switches to %1",
    EVENT_WHENGREATERTHAN: "when %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "timer",
    EVENT_WHENGREATERTHAN_LOUDNESS: "loudness",
    EVENT_BROADCAST: "broadcast %1",
    EVENT_BROADCASTANDWAIT: "broadcast %1 and wait",
    EVENT_WHENKEYPRESSED: "when %1 key pressed",
    EVENT_WHENKEYPRESSED_SPACE: "space",
    EVENT_WHENKEYPRESSED_LEFT: "left arrow",
    EVENT_WHENKEYPRESSED_RIGHT: "right arrow",
    EVENT_WHENKEYPRESSED_DOWN: "down arrow",
    EVENT_WHENKEYPRESSED_UP: "up arrow",
    EVENT_WHENKEYPRESSED_ANY: "any",
    LOOKS_SAYFORSECS: "say %1 for %2 seconds",
    LOOKS_SAY: "say %1",
    LOOKS_HELLO: "Hello!",
    LOOKS_THINKFORSECS: "think %1 for %2 seconds",
    LOOKS_THINK: "think %1",
    LOOKS_HMM: "Hmm...",
    LOOKS_SHOW: "show",
    LOOKS_HIDE: "hide",
    LOOKS_HIDEALLSPRITES: "hide all sprites",
    LOOKS_EFFECT_COLOR: "color",
    LOOKS_EFFECT_FISHEYE: "fisheye",
    LOOKS_EFFECT_WHIRL: "whirl",
    LOOKS_EFFECT_PIXELATE: "pixelate",
    LOOKS_EFFECT_MOSAIC: "mosaic",
    LOOKS_EFFECT_BRIGHTNESS: "brightness",
    LOOKS_EFFECT_GHOST: "ghost",
    LOOKS_CHANGEEFFECTBY: "change %1 effect by %2",
    LOOKS_SETEFFECTTO: "set %1 effect to %2",
    LOOKS_CLEARGRAPHICEFFECTS: "clear graphic effects",
    LOOKS_CHANGESIZEBY: "change size by %1",
    LOOKS_SETSIZETO: "set size to %1 %",
    LOOKS_SIZE: "size",
    LOOKS_CHANGESTRETCHBY: "change stretch by %1",
    LOOKS_SETSTRETCHTO: "set stretch to %1 %",
    LOOKS_SWITCHCOSTUMETO: "switch costume to %1",
    LOOKS_NEXTCOSTUME: "next costume",
    LOOKS_SWITCHBACKDROPTO: "switch backdrop to %1",
    LOOKS_GOTOFRONTBACK: "go to %1 layer",
    LOOKS_GOTOFRONTBACK_FRONT: "front",
    LOOKS_GOTOFRONTBACK_BACK: "back",
    LOOKS_GOFORWARDBACKWARDLAYERS: "go %1 %2 layers",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "forward",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "backward",
    LOOKS_BACKDROPNUMBERNAME: "backdrop %1",
    LOOKS_COSTUMENUMBERNAME: "costume %1",
    LOOKS_NUMBERNAME_NUMBER: "number",
    LOOKS_NUMBERNAME_NAME: "name",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "switch backdrop to %1 and wait",
    LOOKS_NEXTBACKDROP_BLOCK: "next backdrop",
    LOOKS_NEXTBACKDROP: "next backdrop",
    LOOKS_PREVIOUSBACKDROP: "previous backdrop",
    LOOKS_RANDOMBACKDROP: "random backdrop",
    MOTION_MOVESTEPS: "move %1 steps",
    MOTION_TURNLEFT: "turn %1 %2 degrees",
    MOTION_TURNRIGHT: "turn %1 %2 degrees",
    MOTION_POINTINDIRECTION: "point in direction %1",
    MOTION_POINTTOWARDS: "point towards %1",
    MOTION_POINTTOWARDS_POINTER: "mouse-pointer",
    MOTION_POINTTOWARDS_RANDOM: "random direction",
    MOTION_GOTO: "go to %1",
    MOTION_GOTO_POINTER: "mouse-pointer",
    MOTION_GOTO_RANDOM: "random position",
    MOTION_GOTOXY: "go to x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "glide %1 secs to x: %2 y: %3",
    MOTION_GLIDETO: "glide %1 secs to %2",
    MOTION_GLIDETO_POINTER: "mouse-pointer",
    MOTION_GLIDETO_RANDOM: "random position",
    MOTION_CHANGEXBY: "change x by %1",
    MOTION_SETX: "set x to %1",
    MOTION_CHANGEYBY: "change y by %1",
    MOTION_SETY: "set y to %1",
    MOTION_IFONEDGEBOUNCE: "if on edge, bounce",
    MOTION_SETROTATIONSTYLE: "set rotation style %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "left-right",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "don't rotate",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "all around",
    MOTION_XPOSITION: "x position",
    MOTION_YPOSITION: "y position",
    MOTION_DIRECTION: "direction",
    MOTION_SCROLLRIGHT: "scroll right %1",
    MOTION_SCROLLUP: "scroll up %1",
    MOTION_ALIGNSCENE: "align scene %1",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "bottom-left",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "bottom-right",
    MOTION_ALIGNSCENE_MIDDLE: "middle",
    MOTION_ALIGNSCENE_TOPLEFT: "top-left",
    MOTION_ALIGNSCENE_TOPRIGHT: "top-right",
    MOTION_XSCROLL: "x scroll",
    MOTION_YSCROLL: "y scroll",
    MOTION_STAGE_SELECTED: "Stage selected: no motion blocks",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "pick random %1 to %2",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 and %2",
    OPERATORS_OR: "%1 or %2",
    OPERATORS_NOT: "not %1",
    OPERATORS_JOIN: "join %1 %2",
    OPERATORS_JOIN_APPLE: "apple",
    OPERATORS_JOIN_BANANA: "banana",
    OPERATORS_LETTEROF: "letter %1 of %2",
    OPERATORS_LETTEROF_APPLE: "a",
    OPERATORS_LENGTH: "length of %1",
    OPERATORS_CONTAINS: "%1 contains %2?",
    OPERATORS_MOD: "%1 mod %2",
    OPERATORS_ROUND: "round %1",
    OPERATORS_MATHOP: "%1 of %2",
    OPERATORS_MATHOP_ABS: "abs",
    OPERATORS_MATHOP_FLOOR: "floor",
    OPERATORS_MATHOP_CEILING: "ceiling",
    OPERATORS_MATHOP_SQRT: "sqrt",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e ^",
    OPERATORS_MATHOP_10EXP: "10 ^",
	OPERATORS_TOSTRING: "%1 to String",
    PROCEDURES_DEFINITION: "define %1",
    SENSING_TOUCHINGOBJECT: "touching %1?",
    SENSING_TOUCHINGOBJECT_POINTER: "mouse-pointer",
    SENSING_TOUCHINGOBJECT_EDGE: "edge",
    SENSING_TOUCHINGCOLOR: "touching color %1?",
    SENSING_COLORISTOUCHINGCOLOR: "color %1 is touching %2?",
    SENSING_DISTANCETO: "distance to %1",
    SENSING_DISTANCETO_POINTER: "mouse-pointer",
    SENSING_ASKANDWAIT: "ask %1 and wait",
    SENSING_ASK_TEXT: "What's your name?",
    SENSING_ANSWER: "answer",
    SENSING_KEYPRESSED: "key %1 pressed?",
    SENSING_MOUSEDOWN: "mouse down?",
    SENSING_MOUSEX: "mouse x",
    SENSING_MOUSEY: "mouse y",
    SENSING_SETDRAGMODE: "set drag mode %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "draggable",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "not draggable",
    SENSING_LOUDNESS: "loudness",
    SENSING_LOUD: "loud?",
    SENSING_TIMER: "timer",
    SENSING_RESETTIMER: "reset timer",
    SENSING_OF: "%1 of %2",
    SENSING_OF_XPOSITION: "x position",
    SENSING_OF_YPOSITION: "y position",
    SENSING_OF_DIRECTION: "direction",
    SENSING_OF_COSTUMENUMBER: "costume #",
    SENSING_OF_COSTUMENAME: "costume name",
    SENSING_OF_SIZE: "size",
    SENSING_OF_VOLUME: "volume",
    SENSING_OF_BACKDROPNUMBER: "backdrop #",
    SENSING_OF_BACKDROPNAME: "backdrop name",
    SENSING_OF_STAGE: "Stage",
    SENSING_CURRENT: "current %1",
    SENSING_CURRENT_YEAR: "year",
    SENSING_CURRENT_MONTH: "month",
    SENSING_CURRENT_DATE: "date",
    SENSING_CURRENT_DAYOFWEEK: "day of week",
    SENSING_CURRENT_HOUR: "hour",
    SENSING_CURRENT_MINUTE: "minute",
    SENSING_CURRENT_SECOND: "second",
    SENSING_DAYSSINCE2000: "days since 2000",
    SENSING_USERNAME: "username",
    SENSING_USERID: "user id",
    SOUND_PLAY: "start sound %1",
    SOUND_PLAYUNTILDONE: "play sound %1 until done",
    SOUND_STOPALLSOUNDS: "stop all sounds",
    SOUND_SETEFFECTO: "set %1 effect to %2",
    SOUND_CHANGEEFFECTBY: "change %1 effect by %2",
    SOUND_CLEAREFFECTS: "clear sound effects",
    SOUND_EFFECTS_PITCH: "pitch",
    SOUND_EFFECTS_PAN: "pan left/right",
    SOUND_CHANGEVOLUMEBY: "change volume by %1",
    SOUND_SETVOLUMETO: "set volume to %1%",
    SOUND_VOLUME: "volume",
    SOUND_RECORD: "record...",
    CATEGORY_MOTION: "Motion",
    CATEGORY_LOOKS: "Looks",
    CATEGORY_SOUND: "Sound",
    CATEGORY_EVENTS: "Events",
    CATEGORY_CONTROL: "Control",
    CATEGORY_SENSING: "Sensing",
    CATEGORY_OPERATORS: "Operators",
    CATEGORY_VARIABLES: "Variables",
    CATEGORY_MYBLOCKS: "My Blocks",
    DUPLICATE: "Duplicate",
    DELETE: "Delete",
    ADD_COMMENT: "Add Comment",
    REMOVE_COMMENT: "Remove Comment",
    DELETE_BLOCK: "Delete Block",
    DELETE_X_BLOCKS: "Delete %1 Blocks",
    DELETE_ALL_BLOCKS: "Delete all %1 blocks?",
    CLEAN_UP: "Clean up Blocks",
    HELP: "Help",
    UNDO: "Undo",
    REDO: "Redo",
    EDIT_PROCEDURE: "Edit",
    SHOW_PROCEDURE_DEFINITION: "Go to definition",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "Say something...",
    COLOUR_HUE_LABEL: "Color",
    COLOUR_SATURATION_LABEL: "Saturation",
    COLOUR_BRIGHTNESS_LABEL: "Brightness",
    CHANGE_VALUE_TITLE: "Change value:",
    RENAME_VARIABLE: "Rename variable",
    RENAME_VARIABLE_TITLE: 'Rename all "%1" variables to:',
    RENAME_VARIABLE_MODAL_TITLE: "Rename Variable",
    NEW_VARIABLE: "Make a Variable",
    NEW_VARIABLE_TITLE: "New variable name:",
    VARIABLE_MODAL_TITLE: "New Variable",
    VARIABLE_ALREADY_EXISTS: 'A variable named "%1" already exists.',
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: 'A variable named "%1" already exists for another variable of type "%2".',
    DELETE_VARIABLE_CONFIRMATION: 'Delete %1 uses of the "%2" variable?',
    CANNOT_DELETE_VARIABLE_PROCEDURE: 'Can\'t delete the variable "%1" because it\'s part of the definition of the function "%2"',
    DELETE_VARIABLE: 'Delete the "%1" variable',
    NEW_PROCEDURE: "Make a Block",
    PROCEDURE_ALREADY_EXISTS: 'A procedure named "%1" already exists.',
    PROCEDURE_DEFAULT_NAME: "MyBlock",
    PROCEDURE_USED: "To delete a block definition, first remove all uses of the block",
    NEW_LIST: "Make a List",
    NEW_LIST_TITLE: "New list name:",
    LIST_MODAL_TITLE: "New List",
    LIST_ALREADY_EXISTS: 'A list named "%1" already exists.',
    RENAME_LIST_TITLE: 'Rename all "%1" lists to:',
    RENAME_LIST_MODAL_TITLE: "Rename List",
    DEFAULT_LIST_ITEM: "thing",
    DELETE_LIST: 'Delete the "%1" list',
    RENAME_LIST: "Rename list",
    NEW_BROADCAST_MESSAGE: "New message",
    NEW_BROADCAST_MESSAGE_TITLE: "New message name:",
    BROADCAST_MODAL_TITLE: "New Message",
    DEFAULT_BROADCAST_MESSAGE_NAME: "message1",
    CREATE: "New Project",
    OPEN: "Open Project",
    SAVE: "Save Project",
    COMPILE: "Compile Verify",
    UPLOAD: "Verify and Upload",
    MINI_INTRO: "Overlay Intro",
    MINI_WEB: "MATRIX Homepage",
    MINI_ABOUT: "About",
    SWEET_ALERT: {
        ERROR: "Error",
        WARNING: "Warning",
        INFO: "Info",
    },
    BUTTON: {
        OPENFILE: "Yes, Create new file.",
        OPENOLDFILE: "Yes, Open file.",
        CONFIRM: "OK",
        CANCEL: "Cancel",
        ADD_NUM: "Add Number Input",
        ADD_BOOL: "Add Logic Input",
        ADD_TAG: "Add Lable",
        ADD_STRING: "Add String Input",
        DOWNLOAD: "Download Now",
        INTRO_NEXT: "Next",
        INTRO_PREV: "Previous",
        INTRO_DONE: "Done",
        CONSOLE_CONN: "Serial Monitor On/Off",
        CONSOLE_CLEAR: "Clear",
        CONSOLE_CHANGE: "Text/Chart Mode",
        CONSOLE_ZOOM: "Full Screen",
        CLOSE_SAVE: "Yes, Save file",
        CLOSE_NOTSAVE: "No, Don't save",
    },
    TEXT: {
        UPLOAD_SUCCESS: "Compile/Upload Successful",
        UPLOAD_FAILED: "Compile/Upload Failed",
        UPLOAD_FAILED_CANT_CREATE_FILE: "Upload Failed, Can not create temp file.",
        // COMPILE_SUCCESS: "Compile Success",
        // COMPILE_FAILED: "Compile Failed",
        COMPILE_FAILED_EXCEPTION: "Compile Failed, Compiler exception",
        COMPILE_FAILED_CANT_CREATE_FILE: "Compile Failed, Can not create temp file",
        OPEN_FILE: "Are you sure you want to open file without saving?",
        NEW_FILE: "Are you sure you want to create new file without saving?",
        SAVE_FILE_FAILED: "Failed to save file.",
        OPEN_FILE_FAILED: "Failed to open file.",
        CLOSE_APP: "Are you sure you want exit?",
        CLOSE_FILE: "Save your changes to file?",
        SEND: "Send",
        NO_SAME_VAR: "There cannot be variables with the same name in a function!",
        UPDATE_TITLE: "Update Available",
        UPDATE_CURR_VER: "Current Ver: ",
        UPDATE_LATEST_VER: "Latest Ver: ",
    },
    INTRO: {
        TITLE_0: "Welcome!",
        TEXT_0: "Robots can do many things through coding! Let me introduce you to the main features of the software!",
        TITLE_1: "Block Box",
        TEXT_1: "Write C++ programs using blocks. Here are all the categories of blocks listed.",
        TITLE_2: "Code View",
        TEXT_2: "See the C++ code composed of blocks here, and you can also copy it to the Arduino IDE for further programming.",
        TITLE_3: "Information Window",
        TEXT_3: "View the compilation results of the code here, or communicate with the robot using the serial port.",
        TITLE_4: "File Management",
        TEXT_4: "You can save, open programs on your computer, and view more instructions.",
        TITLE_5: "Examples",
        TEXT_5: "Exampls will show you how to get started with Matrix robots easily.",
        TITLE_6: "Control Area",
        TEXT_6: "Select the port to which the robot is connected here, and compile and burn your code.",
        TITLE_7: "Multiple Languages",
        TEXT_7: "Use the globe icon to view language options, then select the language you need.",
        TITLE_8: "All Done!",
        TEXT_8: "These are the main features of the software, let's enter the world of robot programming together!",
    },
    EXAMPLE: {
        TITLE_1: "MATRIX Mini Introduction",
        TITLE_2: "Software Introduction",
        TITLE_3: "MATRIX Assembly Tips",
        TITLE_4: "Basic Car",
        TITLE_5: "Obstacle Avoiding Car",
        TITLE_6: "MJ2 Remote Car",
    },
};

Blockly.ScratchMsgs.locales["zh-cn"] = {
    MINI_SETUP: "Mini初始化%1串口:%2波特率:%3",
    MINI_SETUP2: "初始化%1重复%2",
    MINI_SETRGB: "Mini RGB LED %1 R:%2 G:%3 B:%4",
    MINI_MSET: "Mini直流电机 %1 速度:%2",
    MINI_RCSET: "Mini舵机 %1 角度:%2",
    MINI_BTNGET: "Mini按钮 %1 状态",
    MINI_USGET: "Mini超声波 %1 距离(cm)",
    MINI_DIGET: "Mini %1 数字信号",
    MINI_AIGET: "Mini %1 模拟信号",
    MINI_DOSET: "Mini %1 设置为 %2",
    MINI_I2C_MXCOLOR_SETGAMMA: "Color传感器 %1 设置Gamma校正为 %2",
    MINI_I2C_MXCOLOR_GETCOLORNUMBER: "Color传感器 %1 读取颜色编号",
    MINI_I2C_MXCOLOR_GETCOLOR: "Color传感器 %1 颜色 %2 数值",
    MINI_I2C_MXMOTION_SETFILTER: "Motion传感器 %1 设置滤波器为 %2",
    MINI_I2C_MXMOTION_GETACCEL: "Motion传感器 %1 读取 %2 轴加速度",
    MINI_I2C_MXMOTION_GETGYRO: "Motion传感器 %1 读取 %2 轴陀螺仪",
    MINI_I2C_MXMOTION_GETEULAR: "Motion传感器 %1 欧拉角 %2",
    MINI_I2C_MXLASER_GETDISTANCE: "Laser传感器 %1 距离(mm)",
    MINI_I2C_MXMOTOR_SETPWM: "直流电机盒 %1 %2 设置速度 %3",
    MINI_I2C_MXSERVO_SETANGLE: "舵机盒 %1 %2 设置角度 %3",
    MINI_I2C_MXCTRL_MOTORSET: "MATRIX控制器 %1 %2 设置速度 %3",
    MINI_I2C_MXCTRL_MOTORROUND: "MATRIX控制器 %1 %2 转动圈数 %3",
    MINI_I2C_MXCTRL_MOTORINVERT: "MATRIX控制器 %1 %2 设置反转为 %3",
    MINI_I2C_MXCTRL_SERVOSET: "MATRIX控制器 %1 %2 设置角度 %3",
    MINI_I2C_PIXYCAM_PIXYINIT: "Pixy2摄像头 %1 初始化",
    MINI_I2C_PIXYCAM_GETBLOCK: "Pixy2摄像头 %1 轮询方块信息",
    MINI_I2C_PIXYCAM_INFO: "Pixy2摄像头 %1 读取 %2 数值",
    MINI_I2C_HTCOLOR_GETCOLORNUMBER: "HTColor %1 颜色编号",
    MINI_I2C_HTCOLOR_GETRED: "HTColor %1 红色数值",
    MINI_I2C_HTCOMPASS_GETHEADING: "HTCompass %1 罗盘方位数值",
    MINI_PS2_BEGIN: "MJ2手柄 初始化",
    MINI_PS2_POLLING: "MJ2手柄 轮询数据",
    MINI_PS2_BTN: "MJ2手柄 %1 按钮按下",
    MINI_PS2_JOY: "MJ2手柄 %1 %2蘑菇头数值",
    MINI_SERIAL_PRINT: "串口输出%1",
    MINI_SERIAL_PRINTLN: "串口输出%1并换行",
    MINI_SERIAL_WRITE: "串口写入(ASCII) %1",
    MINI_SERIAL_PRINTAXIS: "串口数据集输出 %1 %2 %3, 间隔 %4 毫秒",
    MINI_SERIAL_AVAILABLE: "串口是否有数据",
    MINI_SERIAL_READ: "串口接收到的数据(ASCII)",
    MINI_MILLIS: "程序已执行的时间(毫秒)",
    MINI_RANDOMSEED: "设置随机函数种子为%1",
    MINI_MAP: "映射 %1 从 %2~%3 到 %4~%5",
    MINI_TIMER_RESET: "計時器 %1 重置",
    MINI_TIMER_READ: "計時器 %1 时间(毫秒)",
    MINI_MVISION_BEGIN: "MVision 初始化", 
    MINI_MVISION_READ1: "MVision 轮询，有数据", 
    MINI_MVISION_READ2: "沒有数据", 
    MINI_MVISION_GETDATA: "MVision %1 数据",
    MINI_HUSKYLENS_BEGIN: "HUSKYLENS 初始化(串口 9600)", 
    MINI_HUSKYLENS_POLLING: "HUSKYLENS 轮询数据", 
    MINI_HUSKYLENS_GETBLOCK: "HUSKYLENS 方框%1數值", 
    MINI_HUSKYLENS_GETARROW: "HUSKYLENS 箭頭%1數值", 
    MINI_HUSKYLENS_ISDETECT: "HUSKYLENS 是否有偵測到物件", 
    MINI_PLACEHOLDER: "-------------------------------",
    CATEGORY__MINI: "Mini Core",
    CATEGORY__MINI_SERIAL: "串口",
    CATEGORY__MINI_MJ2: "手柄",
    CATEGORY__MINI_SENSORS: "侦测",
    CATEGORY__MINI_BOXS: "电机擴展",
    CATEGORY__MINI_THRDPTY: "更多侦测",
    MINICAT_PLACEHOLDER: "-------------------------------",
    CONTROL_FOREVER: "重复执行",
    CONTROL_REPEAT: "重复执行 %1 次",
    CONTROL_IF: "如果 %1 那么",
    CONTROL_ELSE: "否则",
    CONTROL_STOP: "停止",
    CONTROL_STOP_ALL: "全部脚本",
    CONTROL_STOP_THIS: "这个脚本",
    CONTROL_STOP_OTHER: "该角色的其他脚本",
    CONTROL_WAIT: "等待 %1 毫秒",
    CONTROL_WAITUNTIL: "等待 %1",
    CONTROL_REPEATUNTIL: "重复执行直到 %1",
    CONTROL_WHILE: "当 %1 重复执行",
    CONTROL_FOREACH: "对于 %2 中的每个 %1",
    CONTROL_STARTASCLONE: "当作为克隆体启动时",
    CONTROL_CREATECLONEOF: "克隆 %1",
    CONTROL_CREATECLONEOF_MYSELF: "自己",
    CONTROL_DELETETHISCLONE: "删除此克隆体",
    CONTROL_COUNTER: "计数器",
    CONTROL_INCRCOUNTER: "计数器加一",
    CONTROL_CLEARCOUNTER: "计数器归零",
    CONTROL_ALLATONCE: "所有脚本",
    DATA_SETVARIABLETO: "将 %1 设为 %2",
    DATA_CHANGEVARIABLEBY: "将 %1 增加 %2",
    DATA_SHOWVARIABLE: "显示变量 %1",
    DATA_HIDEVARIABLE: "隐藏变量 %1",
    DATA_ADDTOLIST: "将 %1 加入 %2",
    DATA_DELETEOFLIST: "删除 %2 的第 %1 项",
    DATA_DELETEALLOFLIST: "删除 %1 的全部项目",
    DATA_INSERTATLIST: "在 %3 的第 %2 项前插入 %1",
    DATA_REPLACEITEMOFLIST: "将 %2 的第 %1 项替换为 %3",
    DATA_ITEMOFLIST: "%2 的第 %1 项",
    DATA_ITEMNUMOFLIST: "%2 中第一个 %1 的编号",
    DATA_LENGTHOFLIST: "%1 的项目数",
    DATA_LISTCONTAINSITEM: "%1 包含 %2 ?",
    DATA_SHOWLIST: "显示列表 %1",
    DATA_HIDELIST: "隐藏列表 %1",
    DATA_INDEX_ALL: "全部",
    DATA_INDEX_LAST: "末尾",
    DATA_INDEX_RANDOM: "随机",
    EVENT_WHENFLAGCLICKED: "当 %1 被点击",
    EVENT_WHENTHISSPRITECLICKED: "当角色被点击",
    EVENT_WHENSTAGECLICKED: "当舞台被点击",
    EVENT_WHENTOUCHINGOBJECT: "当该角色碰到 %1",
    EVENT_WHENBROADCASTRECEIVED: "当接收到 %1",
    EVENT_WHENBACKDROPSWITCHESTO: "当背景换成 %1",
    EVENT_WHENGREATERTHAN: "当 %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "计时器",
    EVENT_WHENGREATERTHAN_LOUDNESS: "响度",
    EVENT_BROADCAST: "广播 %1",
    EVENT_BROADCASTANDWAIT: "广播 %1 并等待",
    EVENT_WHENKEYPRESSED: "当按下 %1 键",
    EVENT_WHENKEYPRESSED_SPACE: "空格",
    EVENT_WHENKEYPRESSED_LEFT: "←",
    EVENT_WHENKEYPRESSED_RIGHT: "→",
    EVENT_WHENKEYPRESSED_DOWN: "↓",
    EVENT_WHENKEYPRESSED_UP: "↑",
    EVENT_WHENKEYPRESSED_ANY: "任意",
    LOOKS_SAYFORSECS: "说 %1 %2 秒",
    LOOKS_SAY: "说 %1",
    LOOKS_HELLO: "你好！",
    LOOKS_THINKFORSECS: "思考 %1 %2 秒",
    LOOKS_THINK: "思考 %1",
    LOOKS_HMM: "嗯……",
    LOOKS_SHOW: "显示",
    LOOKS_HIDE: "隐藏",
    LOOKS_HIDEALLSPRITES: "隐藏所有角色",
    LOOKS_EFFECT_COLOR: "颜色",
    LOOKS_EFFECT_FISHEYE: "鱼眼",
    LOOKS_EFFECT_WHIRL: "漩涡",
    LOOKS_EFFECT_PIXELATE: "像素化",
    LOOKS_EFFECT_MOSAIC: "马赛克",
    LOOKS_EFFECT_BRIGHTNESS: "亮度",
    LOOKS_EFFECT_GHOST: "虚像",
    LOOKS_CHANGEEFFECTBY: "将 %1 特效增加 %2",
    LOOKS_SETEFFECTTO: "将 %1 特效设定为 %2",
    LOOKS_CLEARGRAPHICEFFECTS: "清除图形特效",
    LOOKS_CHANGESIZEBY: "将大小增加 %1",
    LOOKS_SETSIZETO: "将大小设为 %1",
    LOOKS_SIZE: "大小",
    LOOKS_CHANGESTRETCHBY: "伸缩%1",
    LOOKS_SETSTRETCHTO: "设置伸缩为%1 %",
    LOOKS_SWITCHCOSTUMETO: "换成 %1 造型",
    LOOKS_NEXTCOSTUME: "下一个造型",
    LOOKS_SWITCHBACKDROPTO: "换成 %1 背景",
    LOOKS_GOTOFRONTBACK: "移到最 %1 ",
    LOOKS_GOTOFRONTBACK_FRONT: "前面",
    LOOKS_GOTOFRONTBACK_BACK: "后面",
    LOOKS_GOFORWARDBACKWARDLAYERS: "%1 %2 层",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "前移",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "后移",
    LOOKS_BACKDROPNUMBERNAME: "背景 %1",
    LOOKS_COSTUMENUMBERNAME: "造型 %1",
    LOOKS_NUMBERNAME_NUMBER: "编号",
    LOOKS_NUMBERNAME_NAME: "名称",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "换成 %1 背景并等待",
    LOOKS_NEXTBACKDROP_BLOCK: "下一个背景",
    LOOKS_NEXTBACKDROP: "下一个背景",
    LOOKS_PREVIOUSBACKDROP: "上一个背景",
    LOOKS_RANDOMBACKDROP: "随机背景",
    MOTION_MOVESTEPS: "移动 %1 步",
    MOTION_TURNLEFT: "左转 %1 %2 度",
    MOTION_TURNRIGHT: "右转 %1 %2 度",
    MOTION_POINTINDIRECTION: "面向 %1 方向",
    MOTION_POINTTOWARDS: "面向 %1",
    MOTION_POINTTOWARDS_POINTER: "鼠标指针",
    MOTION_POINTTOWARDS_RANDOM: "随机方向",
    MOTION_GOTO: "移到 %1",
    MOTION_GOTO_POINTER: "鼠标指针",
    MOTION_GOTO_RANDOM: "随机位置",
    MOTION_GOTOXY: "移到 x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "在 %1 秒内滑行到 x: %2 y: %3",
    MOTION_GLIDETO: "在 %1 秒内滑行到 %2",
    MOTION_GLIDETO_POINTER: "鼠标指针",
    MOTION_GLIDETO_RANDOM: "随机位置",
    MOTION_CHANGEXBY: "将x坐标增加 %1",
    MOTION_SETX: "将x坐标设为 %1",
    MOTION_CHANGEYBY: "将y坐标增加 %1",
    MOTION_SETY: "将y坐标设为 %1",
    MOTION_IFONEDGEBOUNCE: "碰到边缘就反弹",
    MOTION_SETROTATIONSTYLE: "将旋转方式设为 %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "左右翻转",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "不可旋转",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "任意旋转",
    MOTION_XPOSITION: "x 坐标",
    MOTION_YPOSITION: "y 坐标",
    MOTION_DIRECTION: "方向",
    MOTION_SCROLLRIGHT: "向右滚动 %1",
    MOTION_SCROLLUP: "向上滚动 %1",
    MOTION_ALIGNSCENE: "和场景 %1 对齐",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "左下角",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "右下角",
    MOTION_ALIGNSCENE_MIDDLE: "中间",
    MOTION_ALIGNSCENE_TOPLEFT: "左上角",
    MOTION_ALIGNSCENE_TOPRIGHT: "右上角",
    MOTION_XSCROLL: "x滚动位置",
    MOTION_YSCROLL: "y滚动位置",
    MOTION_STAGE_SELECTED: "选中了舞台：不可使用运动类积木",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "在 %1 和 %2 之间取随机数",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 且 %2",
    OPERATORS_OR: "%1 或 %2",
    OPERATORS_NOT: "%1 不成立",
    OPERATORS_JOIN: "连接 %1 和 %2",
    OPERATORS_JOIN_APPLE: "苹果",
    OPERATORS_JOIN_BANANA: "香蕉",
    OPERATORS_LETTEROF: "%2 的第 %1 个字符",
    OPERATORS_LETTEROF_APPLE: "果",
    OPERATORS_LENGTH: "%1 的字符数",
    OPERATORS_CONTAINS: "%1 包含 %2 ?",
    OPERATORS_MOD: "%1 除以 %2 的余数",
    OPERATORS_ROUND: "四舍五入 %1",
    OPERATORS_MATHOP: "%1 %2",
    OPERATORS_MATHOP_ABS: "绝对值",
    OPERATORS_MATHOP_FLOOR: "向下取整",
    OPERATORS_MATHOP_CEILING: "向上取整",
    OPERATORS_MATHOP_SQRT: "平方根",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e ^",
    OPERATORS_MATHOP_10EXP: "10 ^",
	OPERATORS_TOSTRING: "%1 轉為字串",
    PROCEDURES_DEFINITION: "定义 %1",
    SENSING_TOUCHINGOBJECT: "碰到 %1 ?",
    SENSING_TOUCHINGOBJECT_POINTER: "鼠标指针",
    SENSING_TOUCHINGOBJECT_EDGE: "舞台边缘",
    SENSING_TOUCHINGCOLOR: "碰到颜色 %1 ?",
    SENSING_COLORISTOUCHINGCOLOR: "颜色 %1 碰到 %2 ?",
    SENSING_DISTANCETO: "到 %1 的距离",
    SENSING_DISTANCETO_POINTER: "鼠标指针",
    SENSING_ASKANDWAIT: "询问 %1 并等待",
    SENSING_ASK_TEXT: "你叫什么名字？",
    SENSING_ANSWER: "回答",
    SENSING_KEYPRESSED: "按下 %1 键?",
    SENSING_MOUSEDOWN: "按下鼠标?",
    SENSING_MOUSEX: "鼠标的x坐标",
    SENSING_MOUSEY: "鼠标的y坐标",
    SENSING_SETDRAGMODE: "将拖动模式设为 %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "可拖动",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "不可拖动",
    SENSING_LOUDNESS: "响度",
    SENSING_LOUD: "响声？",
    SENSING_TIMER: "计时器",
    SENSING_RESETTIMER: "计时器归零",
    SENSING_OF: "%2 的 %1",
    SENSING_OF_XPOSITION: "x 坐标",
    SENSING_OF_YPOSITION: "y 坐标",
    SENSING_OF_DIRECTION: "方向",
    SENSING_OF_COSTUMENUMBER: "造型编号",
    SENSING_OF_COSTUMENAME: "造型名称",
    SENSING_OF_SIZE: "大小",
    SENSING_OF_VOLUME: "音量",
    SENSING_OF_BACKDROPNUMBER: "背景编号",
    SENSING_OF_BACKDROPNAME: "背景名称",
    SENSING_OF_STAGE: "舞台",
    SENSING_CURRENT: "当前时间的 %1",
    SENSING_CURRENT_YEAR: "年",
    SENSING_CURRENT_MONTH: "月",
    SENSING_CURRENT_DATE: "日",
    SENSING_CURRENT_DAYOFWEEK: "星期",
    SENSING_CURRENT_HOUR: "时",
    SENSING_CURRENT_MINUTE: "分",
    SENSING_CURRENT_SECOND: "秒",
    SENSING_DAYSSINCE2000: "2000年至今的天数",
    SENSING_USERNAME: "用户名",
    SENSING_USERID: "用户id",
    SOUND_PLAY: "播放声音 %1",
    SOUND_PLAYUNTILDONE: "播放声音 %1 等待播完",
    SOUND_STOPALLSOUNDS: "停止所有声音",
    SOUND_SETEFFECTO: "将 %1 音效设为 %2",
    SOUND_CHANGEEFFECTBY: "将 %1 音效增加 %2",
    SOUND_CLEAREFFECTS: "清除音效",
    SOUND_EFFECTS_PITCH: "音调",
    SOUND_EFFECTS_PAN: "左右平衡",
    SOUND_CHANGEVOLUMEBY: "将音量增加 %1",
    SOUND_SETVOLUMETO: "将音量设为 %1%",
    SOUND_VOLUME: "音量",
    SOUND_RECORD: "录制…",
    CATEGORY_MOTION: "运动",
    CATEGORY_LOOKS: "外观",
    CATEGORY_SOUND: "声音",
    CATEGORY_EVENTS: "事件",
    CATEGORY_CONTROL: "控制",
    CATEGORY_SENSING: "侦测",
    CATEGORY_OPERATORS: "运算",
    CATEGORY_VARIABLES: "变量",
    CATEGORY_MYBLOCKS: "自制积木",
    DUPLICATE: "复制",
    DELETE: "删除",
    ADD_COMMENT: "添加注释",
    REMOVE_COMMENT: "删除注释",
    DELETE_BLOCK: "删除",
    DELETE_X_BLOCKS: "删除 %1 积木",
    DELETE_ALL_BLOCKS: "删除全部 %1 积木？",
    CLEAN_UP: "整理积木",
    HELP: "帮助",
    UNDO: "撤销",
    REDO: "重做",
    EDIT_PROCEDURE: "编辑",
    SHOW_PROCEDURE_DEFINITION: "查看定义",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "说些什么……",
    COLOUR_HUE_LABEL: "颜色",
    COLOUR_SATURATION_LABEL: "饱和度",
    COLOUR_BRIGHTNESS_LABEL: "亮度",
    CHANGE_VALUE_TITLE: "更改变量：",
    RENAME_VARIABLE: "修改变量名",
    RENAME_VARIABLE_TITLE: "将所有的「%1」变量名改为：",
    RENAME_VARIABLE_MODAL_TITLE: "修改变量名",
    NEW_VARIABLE: "建立一个变量",
    NEW_VARIABLE_TITLE: "新变量名：",
    VARIABLE_MODAL_TITLE: "新建变量",
    VARIABLE_ALREADY_EXISTS: "已经存在名为「%1」的变量。",
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: "已经存在一个名为「%1」的变量，其类型为「%2」。",
    DELETE_VARIABLE_CONFIRMATION: "删除%1处「%2」变量吗？",
    CANNOT_DELETE_VARIABLE_PROCEDURE: "无法删除变量「%1」，因为函数「%2」的定义中用到了它",
    DELETE_VARIABLE: "删除变量「%1」",
    NEW_PROCEDURE: "制作新的积木",
    PROCEDURE_ALREADY_EXISTS: "已经存在名为「%1」的程序。",
    PROCEDURE_DEFAULT_NAME: "MyBlock",
    PROCEDURE_USED: "在删除一个积木定义前，请先把该积木从所有使用的地方删除。",
    NEW_LIST: "建立一个列表",
    NEW_LIST_TITLE: "新的列表名：",
    LIST_MODAL_TITLE: "新建列表",
    LIST_ALREADY_EXISTS: "名为 「%1」 的列表已存在。",
    RENAME_LIST_TITLE: "将所有的「%1」列表改名为：",
    RENAME_LIST_MODAL_TITLE: "修改列表名",
    DEFAULT_LIST_ITEM: "东西",
    DELETE_LIST: "删除「%1」列表",
    RENAME_LIST: "修改列表名",
    NEW_BROADCAST_MESSAGE: "新消息",
    NEW_BROADCAST_MESSAGE_TITLE: "新消息的名称：",
    BROADCAST_MODAL_TITLE: "新消息",
    DEFAULT_BROADCAST_MESSAGE_NAME: "消息1",
    CREATE: "创建",
    OPEN: "打开",
    SAVE: "储存",
    COMPILE: "编译",
    UPLOAD: "烧录",
    MINI_INTRO: "軟件指南",
    MINI_WEB: "MATRIX官方网站",
    MINI_ABOUT: "关于软件",
    SWEET_ALERT: {
        ERROR: "错误",
        WARNING: "注意",
        INFO: "信息",
    },
    BUTTON: {
        OPENFILE: "是，开启新档",
        OPENOLDFILE: "是，开启旧档",
        CONFIRM: "确认",
        CANCEL: "取消",
        ADD_NUM: "新增数字输入",
        ADD_BOOL: "新增布林值输入",
        ADD_TAG: "新增标签",
        ADD_STRING: "新增字串输入",
        DOWNLOAD: "立即下载",
        INTRO_NEXT: "下一个",
        INTRO_PREV: "上一个",
        INTRO_DONE: "完成",
        CONSOLE_CONN: "串口连线开关",
        CONSOLE_CLEAR: "清除内容",
        CONSOLE_CHANGE: "文字/图表模式切换",
        CONSOLE_ZOOM: "全屏切换",
        CLOSE_SAVE: "是，储存档案",
        CLOSE_NOTSAVE: "否，不要储存",
    },
    TEXT: {
        UPLOAD_SUCCESS: "编译/上传完成",
        UPLOAD_FAILED: "编译/上传失败",
        UPLOAD_FAILED_CANT_CREATE_FILE: "上传失败-无法创建暂存档案",
        // COMPILE_SUCCESS: "编译完成",
        // COMPILE_FAILED: "编译失败",
        COMPILE_FAILED_EXCEPTION: "编译失败-编译器异常",
        COMPILE_FAILED_CANT_CREATE_FILE: "编译失败-无法建立暂存档案",
        OPEN_FILE: "目前程式尚未储存，是否要开启旧档？",
        NEW_FILE: "目前程式尚未储存，是否要创建新档案？",
        SAVE_FILE_FAILED: "档案储存失败!",
        OPEN_FILE_FAILED: "档案开启失败!",
        CLOSE_FILE: "您正在关闭软件，是否要储存变更？",
        CLOSE_APP: "确定要关闭软件?",
        SEND: "传送",
        NO_SAME_VAR: "不能有同样名称的变量!",
        UPDATE_TITLE: "有可用的软件更新",
        UPDATE_CURR_VER: "当前版本: ",
        UPDATE_LATEST_VER: "最新版本: ",
    },
    INTRO: {
        TITLE_0: "欢迎使用！",
        TEXT_0: "机器人可以通过编程来做很多事情！让我来为您介绍一下软件的主要功能吧！",
        TITLE_1: "方块箱",
        TEXT_1: "运用方块编写C++程序。这里列出了所有方块的分类。",
        TITLE_2: "代码视图",
        TEXT_2: "在这里看到方块组成的C++代码，也可以将它复制到Arduino IDE进一步编程。",
        TITLE_3: "信息窗口",
        TEXT_3: "在这里检视代码的编译结果，或是使用串口与机器人沟通。",
        TITLE_4: "文件管理",
        TEXT_4: "您可以存储、打开电脑中的程序，也可以查看更多的说明。",
        TITLE_5: "入门课程",
        TEXT_5: "范例项目将展示如何让您轻松上手Matrix机器人。",
        TITLE_6: "控制区",
        TEXT_6: "在此选择机器人连接的端口，及编译、烧录您的程序码。",
        TITLE_7: "多国语言",
        TEXT_7: "使用地球图标查看语言选项，然后选择您所需的语言。",
        TITLE_8: "大功告成！",
        TEXT_8: "以上就是软件的主要功能，一起进入机器人编程的世界吧！",
    },
    EXAMPLE: {
        TITLE_1: "MATRIX Mini介紹",
        TITLE_2: "軟體介面導覽",
        TITLE_3: "MATRIX組裝技巧",
        TITLE_4: "自走小車",
        TITLE_5: "避障小車",
        TITLE_6: "MJ2遙控小車",
    },
};

Blockly.ScratchMsgs.locales["zh-tw"] = {
    MINI_SETUP: "Mini初始化 %1 序列埠:%2 Baud:%3",
    MINI_SETUP2: "設置%1循環%2",
    MINI_SETRGB: "Mini RGB LED %1 R:%2 G:%3 B:%4",
    MINI_MSET: "Mini直流馬達 %1 速度:%2",
    MINI_RCSET: "Mini伺服馬達 %1 角度:%2",
    MINI_BTNGET: "Mini按鈕 %1 狀態",
    MINI_USGET: "Mini超音波 %1 距離(cm)",
    MINI_DIGET: "Mini %1 數位訊號",
    MINI_AIGET: "Mini %1 類比訊號",
    MINI_DOSET: "Mini %1 設為 %2 ",
    MINI_I2C_MXCOLOR_SETGAMMA: "顏色感應器 %1 設定Gamma校正為 %2",
    MINI_I2C_MXCOLOR_GETCOLORNUMBER: "顏色感應器 %1 讀取顏色編號",
    MINI_I2C_MXCOLOR_GETCOLOR: "顏色感應器 %1 顏色 %2 數值",
    MINI_I2C_MXMOTION_SETFILTER: "姿態感應器 %1 設定濾波器為 %2",
    MINI_I2C_MXMOTION_GETACCEL: "姿態感應器 %1 讀取 %2 軸加速度",
    MINI_I2C_MXMOTION_GETGYRO: "姿態感應器 %1 讀取 %2 軸陀螺儀",
    MINI_I2C_MXMOTION_GETEULAR: "姿態感應器 %1 尤拉角 %2",
    MINI_I2C_MXLASER_GETDISTANCE: "雷射感應器 %1 距離(mm)",
    MINI_I2C_MXMOTOR_SETPWM: "DC Box %1 %2 設置速度 %3",
    MINI_I2C_MXSERVO_SETANGLE: "RC Box %1 %2 設置角度 %3",
    MINI_I2C_MXCTRL_MOTORSET: "MATRIX Controller %1 %2 設置速度 %3",
    MINI_I2C_MXCTRL_MOTORROUND: "MATRIX Controller %1 %2 轉動圈數 %3",
    MINI_I2C_MXCTRL_MOTORINVERT: "MATRIX Controller %1 %2 設置反轉為 %3",
    MINI_I2C_MXCTRL_SERVOSET: "MATRIX Controller %1 %2 設置角度 %3",
    MINI_I2C_PIXYCAM_PIXYINIT: "Pixy2鏡頭 %1 初始化",
    MINI_I2C_PIXYCAM_GETBLOCK: "Pixy2鏡頭 %1 輪詢方塊資訊",
    MINI_I2C_PIXYCAM_INFO: "Pixy2鏡頭 %1 讀取 %2 數值",
    MINI_I2C_HTCOLOR_GETCOLORNUMBER: "HTColor %1 顏色編號",
    MINI_I2C_HTCOLOR_GETRED: "HTColor %1 紅色數值",
    MINI_I2C_HTCOMPASS_GETHEADING: "HTCompass %1 羅盤方位數值",
    MINI_PS2_BEGIN: "MJ2搖桿 初始化",
    MINI_PS2_POLLING: "MJ2搖桿 輪詢數據",
    MINI_PS2_BTN: "MJ2搖桿 %1 按鈕按下",
    MINI_PS2_JOY: "MJ2搖桿 %1 %2蘑菇頭數值",
    MINI_SERIAL_PRINT: "Serial序列埠輸出%1",
    MINI_SERIAL_PRINTLN: "Serial序列埠輸出%1並換行",
    MINI_SERIAL_WRITE: "Serial序列埠寫入(ASCII)%1",
    MINI_SERIAL_PRINTAXIS: "Serial序列埠資料集輸出 %1 %2 %3, 間隔 %4 毫秒",
    MINI_SERIAL_AVAILABLE: "Serial序列埠是否有資料",
    MINI_SERIAL_READ: "Serial序列埠接收到的資料(ASCII)",
    MINI_MILLIS: "程式已執行的時間(毫秒)",
    MINI_RANDOMSEED: "設定亂數函式種子為%1",
    MINI_MAP: "映射 %1 從 %2~%3 到 %4~%5",
    MINI_TIMER_RESET: "計時器 %1 重置",
    MINI_TIMER_READ: "計時器 %1 時間(毫秒)",
    MINI_MVISION_BEGIN: "MVision 初始化", 
    MINI_MVISION_READ1: "MVision 輪詢，有資料", 
    MINI_MVISION_READ2: "沒資料", 
    MINI_MVISION_GETDATA: "MVision %1 資料",
    MINI_HUSKYLENS_BEGIN: "HUSKYLENS 初始化(UART 9600)", 
    MINI_HUSKYLENS_POLLING: "HUSKYLENS 輪詢數據", 
    MINI_HUSKYLENS_GETBLOCK: "HUSKYLENS 方框%1數值", 
    MINI_HUSKYLENS_GETARROW: "HUSKYLENS 箭頭%1數值", 
    MINI_HUSKYLENS_ISDETECT: "HUSKYLENS 是否有偵測到物體", 
    MINI_PLACEHOLDER: "-------------------------------",
    CATEGORY__MINI: "Mini Core",
    CATEGORY__MINI_SERIAL: "序列埠",
    CATEGORY__MINI_MJ2: "MJ2搖桿",
    CATEGORY__MINI_SENSORS: "偵測",
    CATEGORY__MINI_BOXS: "馬達擴充",
    CATEGORY__MINI_THRDPTY: "更多偵測",
    MINICAT_PLACEHOLDER: "-------------------------------",
    CONTROL_FOREVER: "重複執行",
    CONTROL_REPEAT: "重複執行 %1 次",
    CONTROL_IF: "如果 %1 那麼",
    CONTROL_ELSE: "否則",
    CONTROL_STOP: "停止",
    CONTROL_STOP_ALL: "全部腳本",
    CONTROL_STOP_THIS: "這個腳本",
    CONTROL_STOP_OTHER: "該角色的其他腳本",
    CONTROL_WAIT: "等待 %1 毫秒",
    CONTROL_WAITUNTIL: "等待 %1",
    CONTROL_REPEATUNTIL: "重複執行直到 %1",
    CONTROL_WHILE: "當 %1 重複執行",
    CONTROL_FOREACH: "對於 %2 中的每個 %1",
    CONTROL_STARTASCLONE: "當作為克隆體啟動時",
    CONTROL_CREATECLONEOF: "克隆 %1",
    CONTROL_CREATECLONEOF_MYSELF: "自己",
    CONTROL_DELETETHISCLONE: "刪除此複製體",
    CONTROL_COUNTER: "計數器",
    CONTROL_INCRCOUNTER: "計數器加一",
    CONTROL_CLEARCOUNTER: "計數器歸零",
    CONTROL_ALLATONCE: "所有腳本",
    DATA_SETVARIABLETO: "將 %1 設為 %2",
    DATA_CHANGEVARIABLEBY: "增加 %1 %2",
    DATA_SHOWVARIABLE: "顯示變數 %1",
    DATA_HIDEVARIABLE: "隱藏變數 %1",
    DATA_ADDTOLIST: "將 %1 加入 %2",
    DATA_DELETEOFLIST: "刪除 %2 的第 %1 項",
    DATA_DELETEALLOFLIST: "刪除 %1 的全部項目",
    DATA_INSERTATLIST: "在 %3 的第 %2 項前插入 %1",
    DATA_REPLACEITEMOFLIST: "將 %2 的第 %1 項替換為 %3",
    DATA_ITEMOFLIST: "%2 的第 %1 項",
    DATA_ITEMNUMOFLIST: "%2 中第一個 %1 的編號",
    DATA_LENGTHOFLIST: "%1 的項目數",
    DATA_LISTCONTAINSITEM: "%1 包含 %2 ?",
    DATA_SHOWLIST: "顯示清單 %1",
    DATA_HIDELIST: "隱藏清單 %1",
    DATA_INDEX_ALL: "全部",
    DATA_INDEX_LAST: "結尾",
    DATA_INDEX_RANDOM: "隨機",
    EVENT_WHENFLAGCLICKED: "當 %1 被點擊",
    EVENT_WHENTHISSPRITECLICKED: "當角色被點擊",
    EVENT_WHENSTAGECLICKED: "當舞台點擊",
    EVENT_WHENTOUCHINGOBJECT: "當角色碰到 %1",
    EVENT_WHENBROADCASTRECEIVED: "當接收到 %1",
    EVENT_WHENBACKDROPSWITCHESTO: "當背景換成 %1",
    EVENT_WHENGREATERTHAN: "當 %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "計時器",
    EVENT_WHENGREATERTHAN_LOUDNESS: "響度",
    EVENT_BROADCAST: "廣播 %1",
    EVENT_BROADCASTANDWAIT: "廣播 %1 並等待",
    EVENT_WHENKEYPRESSED: "當按下 %1 鍵",
    EVENT_WHENKEYPRESSED_SPACE: "空格",
    EVENT_WHENKEYPRESSED_LEFT: "←",
    EVENT_WHENKEYPRESSED_RIGHT: "→",
    EVENT_WHENKEYPRESSED_DOWN: "↓",
    EVENT_WHENKEYPRESSED_UP: "↑",
    EVENT_WHENKEYPRESSED_ANY: "任意",
    LOOKS_SAYFORSECS: "說 %1 %2 秒",
    LOOKS_SAY: "說 %1",
    LOOKS_HELLO: "你好！",
    LOOKS_THINKFORSECS: "思考 %1 %2 秒",
    LOOKS_THINK: "思考 %1",
    LOOKS_HMM: "嗯…",
    LOOKS_SHOW: "顯示",
    LOOKS_HIDE: "隱藏",
    LOOKS_HIDEALLSPRITES: "隱藏所有角色",
    LOOKS_EFFECT_COLOR: "顏色",
    LOOKS_EFFECT_FISHEYE: "魚眼",
    LOOKS_EFFECT_WHIRL: "漩渦",
    LOOKS_EFFECT_PIXELATE: "像素化",
    LOOKS_EFFECT_MOSAIC: "馬賽克",
    LOOKS_EFFECT_BRIGHTNESS: "亮度",
    LOOKS_EFFECT_GHOST: "虛像",
    LOOKS_CHANGEEFFECTBY: "將 %1 特效增加 %2",
    LOOKS_SETEFFECTTO: "將 %1 特效設定為 %2",
    LOOKS_CLEARGRAPHICEFFECTS: "清除圖形特效",
    LOOKS_CHANGESIZEBY: "將大小增加 %1",
    LOOKS_SETSIZETO: "將大小設為 %1",
    LOOKS_SIZE: "大小",
    LOOKS_CHANGESTRETCHBY: "伸縮%1",
    LOOKS_SETSTRETCHTO: "設定伸縮為%1 %",
    LOOKS_SWITCHCOSTUMETO: "換成 %1 造型",
    LOOKS_NEXTCOSTUME: "下一個造型",
    LOOKS_SWITCHBACKDROPTO: "換成 %1 背景",
    LOOKS_GOTOFRONTBACK: "移到最 %1 ",
    LOOKS_GOTOFRONTBACK_FRONT: "前面",
    LOOKS_GOTOFRONTBACK_BACK: "後面",
    LOOKS_GOFORWARDBACKWARDLAYERS: "%1 %2 層",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "前移",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "後移",
    LOOKS_BACKDROPNUMBERNAME: "背景 %1",
    LOOKS_COSTUMENUMBERNAME: "造型 %1",
    LOOKS_NUMBERNAME_NUMBER: "編號",
    LOOKS_NUMBERNAME_NAME: "名稱",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "換成 %1 背景並等待",
    LOOKS_NEXTBACKDROP_BLOCK: "下一個背景",
    LOOKS_NEXTBACKDROP: "下一個背景",
    LOOKS_PREVIOUSBACKDROP: "上一個背景",
    LOOKS_RANDOMBACKDROP: "隨機背景",
    MOTION_MOVESTEPS: "移動 %1 步驟",
    MOTION_TURNLEFT: "左轉 %1 %2 度",
    MOTION_TURNRIGHT: "右轉 %1 %2 度",
    MOTION_POINTINDIRECTION: "面向 %1 方向",
    MOTION_POINTTOWARDS: "面向 %1",
    MOTION_POINTTOWARDS_POINTER: "滑鼠指標",
    MOTION_POINTTOWARDS_RANDOM: "隨機方向",
    MOTION_GOTO: "移到 %1",
    MOTION_GOTO_POINTER: "滑鼠指標",
    MOTION_GOTO_RANDOM: "隨機位置",
    MOTION_GOTOXY: "移到 x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "在 %1 秒內滑到 x: %2 y: %3",
    MOTION_GLIDETO: "在 %1 秒內滑到 %2",
    MOTION_GLIDETO_POINTER: "滑鼠指標",
    MOTION_GLIDETO_RANDOM: "隨機位置",
    MOTION_CHANGEXBY: "將x座標增加 %1",
    MOTION_SETX: "將x座標設為 %1",
    MOTION_CHANGEYBY: "將y座標增加 %1",
    MOTION_SETY: "將y座標設為 %1",
    MOTION_IFONEDGEBOUNCE: "碰到邊緣就反彈",
    MOTION_SETROTATIONSTYLE: "將旋轉方式設為 %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "左右翻轉",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "不可旋轉",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "任意旋轉",
    MOTION_XPOSITION: "x 座標",
    MOTION_YPOSITION: "y 座標",
    MOTION_DIRECTION: "方向",
    MOTION_SCROLLRIGHT: "向右捲動 %1",
    MOTION_SCROLLUP: "向上捲動 %1",
    MOTION_ALIGNSCENE: "與場景 %1 對齊",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "左下角",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "右下角",
    MOTION_ALIGNSCENE_MIDDLE: "中間",
    MOTION_ALIGNSCENE_TOPLEFT: "左上角",
    MOTION_ALIGNSCENE_TOPRIGHT: "右上角",
    MOTION_XSCROLL: "x滾動位置",
    MOTION_YSCROLL: "y滾動位置",
    MOTION_STAGE_SELECTED: "選中了舞台：不可使用運動類積木",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "在 %1 和 %2 之間取隨機數",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 且 %2",
    OPERATORS_OR: "%1 或 %2",
    OPERATORS_NOT: "%1 不成立",
    OPERATORS_JOIN: "連接 %1 和 %2",
    OPERATORS_JOIN_APPLE: "蘋果",
    OPERATORS_JOIN_BANANA: "香蕉",
    OPERATORS_LETTEROF: "%2 的第 %1 個字元",
    OPERATORS_LETTEROF_APPLE: "果實",
    OPERATORS_LENGTH: "%1 的字元數",
    OPERATORS_CONTAINS: "%1 包含 %2 ?",
    OPERATORS_MOD: "%1 除以 %2 的餘數",
    OPERATORS_ROUND: "四捨五入 %1",
    OPERATORS_MATHOP: "%1 %2",
    OPERATORS_MATHOP_ABS: "絕對值",
    OPERATORS_MATHOP_FLOOR: "向下取整",
    OPERATORS_MATHOP_CEILING: "向上取整",
    OPERATORS_MATHOP_SQRT: "平方根",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e ^",
    OPERATORS_MATHOP_10EXP: "10 ^",
	OPERATORS_TOSTRING: "%1 轉為字串",
    PROCEDURES_DEFINITION: "定義 %1",
    SENSING_TOUCHINGOBJECT: "碰到 %1 ?",
    SENSING_TOUCHINGOBJECT_POINTER: "滑鼠指標",
    SENSING_TOUCHINGOBJECT_EDGE: "舞台邊緣",
    SENSING_TOUCHINGCOLOR: "碰到顏色 %1 ?",
    SENSING_COLORISTOUCHINGCOLOR: "顏色 %1 碰到 %2 ?",
    SENSING_DISTANCETO: "到 %1 的距離",
    SENSING_DISTANCETO_POINTER: "滑鼠指標",
    SENSING_ASKANDWAIT: "詢問 %1 並等待",
    SENSING_ASK_TEXT: "你叫什麼名字？",
    SENSING_ANSWER: "回答",
    SENSING_KEYPRESSED: "按下 %1 鍵?",
    SENSING_MOUSEDOWN: "按下滑鼠?",
    SENSING_MOUSEX: "滑鼠的x座標",
    SENSING_MOUSEY: "滑鼠的y座標",
    SENSING_SETDRAGMODE: "將拖曳模式設為 %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "可拖曳",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "不可拖曳",
    SENSING_LOUDNESS: "響度",
    SENSING_LOUD: "響聲？",
    SENSING_TIMER: "計時器",
    SENSING_RESETTIMER: "計時器歸零",
    SENSING_OF: "%2 的 %1",
    SENSING_OF_XPOSITION: "x 座標",
    SENSING_OF_YPOSITION: "y 座標",
    SENSING_OF_DIRECTION: "方向",
    SENSING_OF_COSTUMENUMBER: "造型編號",
    SENSING_OF_COSTUMENAME: "造型名稱",
    SENSING_OF_SIZE: "大小",
    SENSING_OF_VOLUME: "音量",
    SENSING_OF_BACKDROPNUMBER: "背景編號",
    SENSING_OF_BACKDROPNAME: "背景名稱",
    SENSING_OF_STAGE: "舞台",
    SENSING_CURRENT: "目前時間的 %1",
    SENSING_CURRENT_YEAR: "年",
    SENSING_CURRENT_MONTH: "月",
    SENSING_CURRENT_DATE: "日",
    SENSING_CURRENT_DAYOFWEEK: "星期",
    SENSING_CURRENT_HOUR: "時",
    SENSING_CURRENT_MINUTE: "分",
    SENSING_CURRENT_SECOND: "秒",
    SENSING_DAYSSINCE2000: "2000年至今的天數",
    SENSING_USERNAME: "使用者名稱",
    SENSING_USERID: "用戶id",
    SOUND_PLAY: "播放聲音 %1",
    SOUND_PLAYUNTILDONE: "播放聲音 %1 等待播完",
    SOUND_STOPALLSOUNDS: "停止所有聲音",
    SOUND_SETEFFECTO: "將 %1 音效設為 %2",
    SOUND_CHANGEEFFECTBY: "增加 %1 音效 %2",
    SOUND_CLEAREFFECTS: "清除音效",
    SOUND_EFFECTS_PITCH: "音調",
    SOUND_EFFECTS_PAN: "左右平衡",
    SOUND_CHANGEVOLUMEBY: "音量增加 %1",
    SOUND_SETVOLUMETO: "將音量設為 %1%",
    SOUND_VOLUME: "音量",
    SOUND_RECORD: "錄音…",
    CATEGORY_MOTION: "運動",
    CATEGORY_LOOKS: "外觀",
    CATEGORY_SOUND: "聲音",
    CATEGORY_EVENTS: "事件",
    CATEGORY_CONTROL: "控制",
    CATEGORY_SENSING: "偵測",
    CATEGORY_OPERATORS: "運算",
    CATEGORY_VARIABLES: "變數",
    CATEGORY_MYBLOCKS: "自製積木",
    DUPLICATE: "複製",
    DELETE: "刪除",
    ADD_COMMENT: "新增註解",
    REMOVE_COMMENT: "刪除註解",
    DELETE_BLOCK: "刪除",
    DELETE_X_BLOCKS: "刪除 %1 積木",
    DELETE_ALL_BLOCKS: "刪除全部 %1 積木？",
    CLEAN_UP: "整理積木",
    HELP: "幫助",
    UNDO: "撤銷",
    REDO: "重做",
    EDIT_PROCEDURE: "編輯",
    SHOW_PROCEDURE_DEFINITION: "查看定義",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "說些什麼…",
    COLOUR_HUE_LABEL: "顏色",
    COLOUR_SATURATION_LABEL: "飽和度",
    COLOUR_BRIGHTNESS_LABEL: "亮度",
    CHANGE_VALUE_TITLE: "更改變數：",
    RENAME_VARIABLE: "修改變數名",
    RENAME_VARIABLE_TITLE: "將所有的「%1」變數名稱改為：",
    RENAME_VARIABLE_MODAL_TITLE: "修改變數名稱",
    NEW_VARIABLE: "建立一個變數",
    NEW_VARIABLE_TITLE: "新變數名：",
    VARIABLE_MODAL_TITLE: "新變數",
    VARIABLE_ALREADY_EXISTS: "已經存在名為「%1」的變數。 ",
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: "已經存在一個名為「%1」的變量，其類型為「%2」。 ",
    DELETE_VARIABLE_CONFIRMATION: "刪除%1處「%2」變數嗎？ ",
    CANNOT_DELETE_VARIABLE_PROCEDURE: "無法刪除變數「%1」，因為函數「%2」的定義中用到了它",
    DELETE_VARIABLE: "刪除變數“%1”",
    NEW_PROCEDURE: "製作新的積木",
    PROCEDURE_ALREADY_EXISTS: "已經存在名為「%1」的程式。 ",
    PROCEDURE_DEFAULT_NAME: "MyBlock",
    PROCEDURE_USED: "在刪除一個積木定義前，請先把該積木從所有使用的地方刪除。",
    NEW_LIST: "建立一個清單",
    NEW_LIST_TITLE: "新的清單名稱：",
    LIST_MODAL_TITLE: "新清單",
    LIST_ALREADY_EXISTS: "名為 “%1” 的清單已存在。 ",
    RENAME_LIST_TITLE: "將所有的「%1」清單改名為：",
    RENAME_LIST_MODAL_TITLE: "修改清單名稱",
    DEFAULT_LIST_ITEM: "東西",
    DELETE_LIST: "刪除「%1」清單",
    RENAME_LIST: "修改清單名稱",
    NEW_BROADCAST_MESSAGE: "新訊息",
    NEW_BROADCAST_MESSAGE_TITLE: "新訊息的名稱：",
    BROADCAST_MODAL_TITLE: "新訊息",
    DEFAULT_BROADCAST_MESSAGE_NAME: "訊息1",
    CREATE: "新建檔案",
    OPEN: "開啟舊檔",
    SAVE: "儲存檔案",
    COMPILE: "編譯驗證",
    UPLOAD: "編譯並燒錄",
    MINI_INTRO: "軟體指南",
    MINI_WEB: "MATRIX官方網站",
    MINI_ABOUT: "關於軟體",
    SWEET_ALERT: {
        ERROR: "錯誤",
        WARNING: "注意",
        INFO: "資訊",
    },
    BUTTON: {
        OPENFILE: "是，建立新檔案",
        OPENOLDFILE: "是，開啟檔案",
        CONFIRM: "確認",
        CANCEL: "取消",
        ADD_NUM: "新增數字輸入",
        ADD_BOOL: "新增邏輯輸入",
        ADD_TAG: "新增標籤",
        ADD_STRING: "新增文字輸入",
        DOWNLOAD: "立即下載",
        INTRO_NEXT: "下一個",
        INTRO_PREV: "上一個",
        INTRO_DONE: "完成",
        CONSOLE_CONN: "序列埠連線開關",
        CONSOLE_CLEAR: "清除內容",
        CONSOLE_CHANGE: "文字/圖表模式切換",
        CONSOLE_ZOOM: "全螢幕切換",
        CLOSE_SAVE: "是，儲存檔案",
        CLOSE_NOTSAVE: "否，不要儲存",
    },
    TEXT: {
        UPLOAD_SUCCESS: "編譯/燒錄成功",
        UPLOAD_FAILED: "編譯/燒錄失敗",
        UPLOAD_FAILED_CANT_CREATE_FILE: "上傳失敗-無法建立暫存檔案",
        // COMPILE_SUCCESS: "編譯完成",
        // COMPILE_FAILED: "編譯失敗",
        COMPILE_FAILED_EXCEPTION: "編譯失敗-編譯器異常",
        COMPILE_FAILED_CANT_CREATE_FILE: "編譯失敗-無法建立暫存檔案",
        OPEN_FILE: "目前程式尚未儲存，是否要開啟舊檔？",
        NEW_FILE: "目前程式尚未儲存，是否要建立新檔案？",
        SAVE_FILE_FAILED: "檔案儲存失敗!",
        OPEN_FILE_FAILED: "檔案開啟失敗!",
        CLOSE_APP: "確定要關閉軟體?",
        CLOSE_FILE: "您正在關閉軟體，是否要儲存變更？",
        SEND: "傳送",
        NO_SAME_VAR: "不能有同樣名稱的變數!",
        UPDATE_TITLE: "有可用的軟體更新",
        UPDATE_CURR_VER: "目前版本: ",
        UPDATE_LATEST_VER: "最新版本: ",
    },
    INTRO: {
        TITLE_0: "歡迎使用！",
        TEXT_0: "機器人可以透過程式來做很多事情！讓我來為您介紹一下軟體的主要功能吧！",
        TITLE_1: "方塊箱",
        TEXT_1: "這裡列出了所有方塊的分類，運用這些方塊來撰寫C++程式。",
        TITLE_2: "代碼檢視",
        TEXT_2: "在這裡看到方塊組成的C++代碼，也可以將它複製到Arduino IDE進一步編程。",
        TITLE_3: "資訊窗口",
        TEXT_3: "在這裡檢視代碼的編譯結果，或是使用序列埠與機器人溝通。",
        TITLE_4: "檔案管理",
        TEXT_4: "您可以儲存、開啟電腦中的程式，也可以查看更多的說明。",
        TITLE_5: "入門課程",
        TEXT_5: "範例專案將展示如何讓您輕鬆上手Matrix機器人。",
        TITLE_6: "控制區",
        TEXT_6: "在此選擇機器人連接的端口，及編譯、燒錄您的程式碼。",
        TITLE_7: "多國語言",
        TEXT_7: "使用地球圖示查看語言選項，然後選擇您所需的語言。",
        TITLE_8: "大功告成！",
        TEXT_8: "以上就是軟體的主要功能，一起進入機器人編程的世界吧！",
    },
    EXAMPLE: {
        TITLE_1: "MATRIX Mini介紹",
        TITLE_2: "軟體介面導覽",
        TITLE_3: "MATRIX組裝技巧",
        TITLE_4: "自走小車",
        TITLE_5: "避障小車",
        TITLE_6: "MJ2遙控小車",
    },
};
